package ru.sutochno.tests.web;

import ru.sutochno.api.models.ObjectProperties;
import ru.sutochno.api.models.Properties;

import java.io.IOException;

public class TestData extends TestBase {

    ObjectProperties objectProperties = new ObjectProperties();

    public TestData() throws IOException {
    }

    public ObjectProperties getChangeProperties(Integer id) {
        objectProperties.setObjectId(id);
        Properties properties = new Properties();
        properties.setRooms(guestsVolume.getNumberOfRooms());
        properties.setAddBathroom(equipment.getBathroomEquipments().get("дополнительная ванная"));
        properties.setAddToilet(equipment.getBathroomEquipments().get("дополнительный туалет"));
        properties.setArbor(equipment.getYardEquipment().get("беседка"));
        properties.setArea(generalInfo.getSquare().toString());
        properties.setAtticFloor(generalInfo.isAttic());
        properties.setBsofaBed(guestsVolume.getBeds().getSofaBed());
        properties.setBabyBed(equipment.getChildrenEquipment().get("детская кроватка"));
        properties.setBabyBedM(equipment.getChildrenEquipment().get("кровать-манеж"));
        properties.setBabyChangTable(equipment.getChildrenEquipment().get("пеленальный стол"));
        properties.setBabyPotty(equipment.getChildrenEquipment().get("детский горшок"));
        properties.setBabychair(equipment.getChildrenEquipment().get("стульчик для кормления"));
        properties.setBalcony(equipment.getHomeFacilities().get("балкон"));
        properties.setBar(equipment.getKitchenEquipment().get("барная стойка"));
        properties.setBarbecue(equipment.getYardEquipment().get("барбекю/мангал"));
        properties.setBarbecueFacilities(equipment.getYardEquipment().get("принадлежности для барбекю"));
        properties.setBath1(equipment.getYardEquipment().get("баня (на территории)"));
        properties.setBathrobe(equipment.getBathroomEquipments().get("халат"));
        properties.setBathrooms(equipment.getBathroomEquipments().get("ванна"));
        properties.setBedclothes(equipment.getHomeFacilities().get("постельное бельё"));
        properties.setBedrooms(guestsVolume.getNumberOfBedrooms());
//        properties.setBeforeDays(data.beforeDays.toString());
//        properties.setBeforeHours(data.beforeHours.toString());
        properties.setBidet(equipment.getBathroomEquipments().get("биде"));
        properties.setBilliards1(equipment.getRestEquipment().get("бильярд"));
        properties.setBlender(equipment.getKitchenEquipment().get("блендер"));
        properties.setBluRayPl(equipment.getRestEquipment().get("blu-ray плеер"));
        properties.setBoat(equipment.getYardEquipment().get("лодка"));
        properties.setBooks(equipment.getRestEquipment().get("книги"));
        properties.setCarpetCovering(equipment.getHouseEquipment().get("ковровое покрытие"));
        properties.setCheckIn(bookingTerm.getCheckIn());
//        properties.setCheckInEarly(data.checkInEarly[1]);
        properties.setCheckOut(bookingTerm.getCheckOut());
//        properties.setCheckOutEarly(data.checkOutEarly[1]);
        properties.setChildrenAge(bookingTerm.getPlacementTerm().getChildrenAge().toString());
//        properties.setCleaning(2);
        properties.setCleaningProducts(equipment.getHouseEquipment().get("чистящие средства"));
        properties.setClothesdryer(equipment.getHouseEquipment().get("сушилка для белья"));
//        properties.setCntBathrooms(data.cntBathrooms);
//        properties.setCntBathroomsToilet(data.cntBathroomsToilet);
//        properties.setCntToilets(data.cntToilets);
        properties.setCoffeeMachine(equipment.getKitchenEquipment().get("кофемашина"));
        properties.setCoffeemaker(equipment.getKitchenEquipment().get("кофеварка"));
        properties.setCondition(equipment.getHomeFacilities().get("кондиционер"));
        properties.setConsol(equipment.getRestEquipment().get("игровая консоль"));
        properties.setCrockery(equipment.getKitchenEquipment().get("посуда и принадлежности"));
        properties.setCshower(equipment.getBathroomEquipments().get("общий душ/душевая"));
        properties.setCtable(equipment.getHouseEquipment().get("журнальный столик"));
        properties.setCupboard(equipment.getHouseEquipment().get("шкаф"));
        properties.setCutlery(equipment.getKitchenEquipment().get("столовые приборы"));
        properties.setDeckchair(equipment.getYardEquipment().get("шезлонги"));
        properties.setDeepfreeze(equipment.getKitchenEquipment().get("морозильник"));
        properties.setDeposit(price.getDeposit());
        properties.setDescription(description.getDescription());
        properties.setDesktop(equipment.getHouseEquipment().get("рабочий стол"));
        properties.setDinnerTable(equipment.getKitchenEquipment().get("обеденный стол"));
        properties.setDishwasher(equipment.getKitchenEquipment().get("посудомоечная машина"));
        properties.setDisks(equipment.getRestEquipment().get("CD/DVD диски"));
//        properties.setDocuments(data.documents);
        properties.setDoubleBed(guestsVolume.getBeds().getDoubleBed());
        properties.setDryingMachine(equipment.getHouseEquipment().get("сушильная машина"));
        properties.setDvd(equipment.getRestEquipment().get("DVD-проигрыватель"));
        properties.setElectricBlankets(equipment.getHouseEquipment().get("одеяла с электроподогревом"));
        properties.setElectricrange(equipment.getKitchenEquipment().get("электроплита"));
//        properties.setExtLinks("http://another_resourse.com");
        properties.setFan(equipment.getHouseEquipment().get("вентилятор"));
        properties.setFireplace(equipment.getHouseEquipment().get("камин"));
        properties.setFloor(generalInfo.getFloorOfFlat());
        properties.setFoldingBed(equipment.getHouseEquipment().get("раскладная кровать"));
        properties.setGames(equipment.getChildrenEquipment().get("игры/игрушки для детей"));
        properties.setGarage(equipment.getYardEquipment().get("гараж"));
        properties.setGasstove(equipment.getKitchenEquipment().get("газовая плита"));
        properties.setGethering(price.getGethering());
        properties.setGeyser(equipment.getHouseEquipment().get("газовый водонагреватель"));
        properties.setGfurniture(equipment.getYardEquipment().get("садовая мебель"));
        properties.setGridiron(equipment.getYardEquipment().get("футбольное поле"));
        properties.setGym(equipment.getYardEquipment().get("спортивный зал"));
        properties.setHairdryer(equipment.getBathroomEquipments().get("фен"));
        properties.setHammok(equipment.getYardEquipment().get("гамак"));
        properties.setHeater(equipment.getHouseEquipment().get("обогреватель"));
        properties.setHeating(equipment.getHouseEquipment().get("центральное отопление"));
        properties.setHighChairForChild(equipment.getChildrenEquipment().get("высокий стул для ребенка"));
        properties.setHygienicShower(equipment.getBathroomEquipments().get("гигиенический душ"));
        properties.setIntercom(equipment.getHouseEquipment().get("домофон"));
        properties.setInternet(equipment.getHouseEquipment().get("проводной интернет"));
        properties.setIron(equipment.getHouseEquipment().get("утюг с гладильной доской"));
        properties.setIsChildren(bookingTerm.getPlacementTerm().getChildren().getValue().toString());
////todo        properties.setIsGuestNegative(random.nextBoolean());
        properties.setIsolation(equipment.getHomeFacilities().get("самоизоляция разрешена"));
        properties.setJacuzzi(equipment.getHouseEquipment().get("джакузи (гидромассажная ванна)"));
        properties.setKettle(equipment.getHomeFacilities().get("электрический чайник"));
        properties.setKingBed(1);
        properties.setKitchen(equipment.getKitchenEquipment().get("кухонный гарнитур"));
//        properties.setKitchenFlat(data.kitchenFlat);
        properties.setLaminate(equipment.getHouseEquipment().get("ламинат"));
        properties.setLaptop(equipment.getRestEquipment().get("ноутбук"));
        properties.setLift(generalInfo.isElevator());
        properties.setLinoleum(equipment.getHouseEquipment().get("линолеум"));
        properties.setMaxFloor(generalInfo.descFloors());
        properties.setMaxGuests(guestsVolume.getMaxGuests());
        properties.setMicrowave(equipment.getHomeFacilities().get("СВЧ-печь"));
//        properties.setMinNights(data.minNights[1]);
        properties.setMiniBar(equipment.getKitchenEquipment().get("мини-бар"));
        properties.setMosquitoNet(equipment.getHouseEquipment().get("москитная сетка"));
        properties.setMulticooker(equipment.getKitchenEquipment().get("мультиварка"));
        properties.setMusicCenter(equipment.getRestEquipment().get("музыкальный центр"));
        properties.setNameObject(description.getPublicName());
        properties.setOutdoorDiningArea(equipment.getYardEquipment().get("обеденная зона на улице"));
        properties.setOutdoorFurniture(equipment.getYardEquipment().get("мебель на улице"));
        properties.setOven(equipment.getKitchenEquipment().get("духовка"));
        properties.setParasol(equipment.getYardEquipment().get("пляжный зонтик"));
        properties.setParking(equipment.getYardEquipment().get("парковка"));
        properties.setParty(bookingTerm.getPlacementTerm().getParty().getValue().toString());
        properties.setPatio(equipment.getYardEquipment().get("патио"));
        properties.setPc(equipment.getHouseEquipment().get("персональный компьютер"));
        properties.setPets(bookingTerm.getPlacementTerm().getPets().getValue().toString());
        properties.setPlayground(equipment.getYardEquipment().get("игровая площадка"));
        properties.setPrecostPercent(18);
        properties.setQualityRepair(repairmentQuality.getValue().toString());
        properties.setRadio(equipment.getRestEquipment().get("радио"));
        properties.setRefrigerator(equipment.getKitchenEquipment().get("холодильник"));
        properties.setSafe(equipment.getHouseEquipment().get("сейф"));
        properties.setSafeWindow(equipment.getChildrenEquipment().get("защита на окнах"));
        properties.setSauna(equipment.getBathroomEquipments().get("сауна"));
        properties.setSeatingArea(equipment.getHouseEquipment().get("гостиный уголок"));
        properties.setSecurity(equipment.getYardEquipment().get("охраняемая территория"));
        properties.setSelfNumberObject(description.getPrivateName());
        properties.setSharedBathroom(equipment.getBathroomEquipments().get("общая ванная комната"));
        properties.setSharedToilet(equipment.getBathroomEquipments().get("общий туалет"));
        properties.setShower(equipment.getBathroomEquipments().get("душ"));
        properties.setSingleBed(guestsVolume.getBeds().getSingleBed());
        properties.setSlippers(equipment.getBathroomEquipments().get("тапочки"));
        properties.setSmoking(bookingTerm.getPlacementTerm().getSmoking().getValue().toString());
        properties.setSofa(equipment.getHouseEquipment().get("диван"));
        properties.setSofaBed(equipment.getHouseEquipment().get("диван-кровать"));
        properties.setSoundproofing(equipment.getHouseEquipment().get("звукоизоляция"));
        properties.setSteelDoor(equipment.getHouseEquipment().get("металлическая дверь"));
        properties.setSuperKingBed(guestsVolume.getBeds().getSuperKingBed());
        properties.setSwimpool1(equipment.getYardEquipment().get("бассейн"));
        properties.setSwing(equipment.getYardEquipment().get("детские качели"));
        properties.setTabletennis(equipment.getRestEquipment().get("настольный теннис"));
        properties.setTelephone(equipment.getHouseEquipment().get("телефон"));
        properties.setTerrace(equipment.getYardEquipment().get("терраса"));
        properties.setTgames(equipment.getRestEquipment().get("настольные игры"));
        properties.setTiledMarbleFloor(equipment.getHouseEquipment().get("плиточный/мраморный пол"));
        properties.setToaster(equipment.getKitchenEquipment().get("тостер"));
        properties.setToiletries(equipment.getBathroomEquipments().get("туалетные принадлежности"));
        properties.setTowels(equipment.getBathroomEquipments().get("полотенца"));
        properties.setTransfer(transfer.isTransfer());
        properties.setTransferDescription(transfer.getTransferTerm());
        properties.setTurka(equipment.getKitchenEquipment().get("турка для приготовления кофе"));
        properties.setTv(equipment.getHomeFacilities().get("телевизор"));
        properties.setTvCable(equipment.getRestEquipment().get("кабельное ТВ"));
        properties.setTvFree(equipment.getRestEquipment().get("эфирное ТВ"));
        properties.setTvSattelite(equipment.getRestEquipment().get("спутниковое ТВ"));
// todo view map        properties.setVCity(view.get("на город"));
//        properties.setVFore(data.view.get("на лес"));
//        properties.setVLake(data.view.get("на озеро"));
//        properties.setVMoun(data.view.get("на горы"));
//        properties.setVPark(data.view.get("на город"));
//        properties.setVRive(data.view.get("на реку"));
        properties.setVSeas(true);
//        properties.setVStrt(data.view.get("на парк"));
//        properties.setVYard(data.view.get("во двор"));
        properties.setVeranda(equipment.getYardEquipment().get("веранда"));
        properties.setWardrobe(equipment.getHouseEquipment().get("гардеробная"));
        properties.setWashmachine(equipment.getHouseEquipment().get("стиральная машина"));
        properties.setWaterfilter(equipment.getKitchenEquipment().get("фильтр для воды"));
        properties.setWheater(equipment.getHouseEquipment().get("водонагреватель"));
//        properties.setWifi(equipment.getHomeFacilities().get("беспроводной интернет wi-fi"));
        properties.setWoodenParquetFloor(equipment.getHouseEquipment().get("деревянный/паркетный пол"));
        properties.setYarusBed(1);
        objectProperties.setProperties(properties);
        return objectProperties;
    }
}